# don't print a newline at the start of the prompt
add_newline = false

[package]
style = "cyan"

[character]
success_symbol = '[â†³](bold cyan)'

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[git_branch]
symbol = "ğŸŒ±  "
# symbol = "â™† "

[git_state]
rebase = "REBASING ğŸ˜"
merge = "MERGING ğŸ¥³"
revert = "REVERTING ğŸ˜“"

[time]
style = "magenta"
use_12hr = false
disabled = false
time_format = "%I:%M%p"
