# don't print a newline at the start of the prompt
add_newline = false

[package]
style = "cyan"

[character]
symbol = 'â†³ '

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[git_branch]
symbol = "ðŸŒ±  "
# symbol = "â™† "

[git_state]
rebase = "REBASING ðŸ˜Ž"
merging = "MERGING ðŸ¥³"
reverting = "REVERTING ðŸ˜“"
progress_divider = "â­„ "

[time]
style = "magenta"
use_12hr = false
disabled = false
time_format = "%I:%M%p"
